name = "logue-api"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "DB"
database_name = "logue-db"
database_id = "0499e2e6-2639-4bd9-aadc-aee2f21b1546"

[observability]
enabled = true
